services:
  storage:
    image: redis
    volumes:
      - ./data:/data
  counter:
    image: node:20.10
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - PORT=3003
      - REDIS_URL=redis://storage
    ports:
      - 83:3003
    command: npm run dev
    depends_on:
      - storage
      